spring:
  application:
    name:
      ConsumerApplication
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/data_db?retryWrites=true&w=majority}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:29092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.demo.consumerapplication.model.event.DataEvent


logging:
  level:
    root: INFO
    com.demo.consumerapplication: DEBUG

topic:
  data-topic: data-topic

server:
  port: 8082