version: '3.8'
services:
  data-mongo:
    hostname: data-mongo
    image: mongo:5.0.0
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "mongod","--bind_ip_all","--replSet","rs0" ]
  mongo-setup:
    image: mongo:5.0.0
    depends_on:
      - data-mongo
    volumes:
      - ./scripts/mongo-init.js:/scripts/mongo-init.js
    links:
      - data-mongo:data-mongo
    restart: "no"
    entrypoint: [ "bash", "-c", "sleep 10 && mongo --host data-mongo:27017 /scripts/mongo-init.js" ]
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - 7070:8080
    environment:
      KAFKA_BROKERS: kafka:9092